// <auto-generated />
using System;
using CSC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSC.Migrations
{
    [DbContext(typeof(CSCContext))]
    [Migration("20190409140232_Usuario")]
    partial class Usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSC.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("CNPJ");

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("DataInicio");

                    b.Property<string>("Logradouro");

                    b.Property<string>("NomeFantasia");

                    b.Property<int>("Numero");

                    b.Property<string>("RazaoSocial");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("CSC.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Admissao");

                    b.Property<DateTime?>("Demissao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Veiculo")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("CSC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Senha");

                    b.Property<int?>("funcionarioId");

                    b.Property<string>("nomeLogon");

                    b.HasKey("Id");

                    b.HasIndex("funcionarioId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CSC.Models.User", b =>
                {
                    b.HasOne("CSC.Models.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
